apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-api-pvc
  namespace: hard-multi-tenancy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual