apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-api-role
  namespace: hard-multi-tenancy
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]