apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-api-role-binding
  namespace: hard-multi-tenancy
subjects:
- kind: User
  name: "sample-api"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sample-api-role
  apiGroup: rbac.authorization.k8s.io